name: Practice project
on: issues
jobs:
    issues:
        runs-on: ubuntu-latest
        steps:
            - name: Output contex details!
              run: echo "${{ toJson(github.event.issue.body)}}"